/**
 * Regression: a doomed turn must not destroy a pending resume.
 *
 * Reconstructed from a real local incident on 2026-08-18 (thread
 * 1a2d462e-2f4f-468f-ad37-285ef5095f3c), where three threads were rejected by the same
 * five_hour window within 32 seconds of each other and only two came back.
 *
 * Ground truth from the projection and the reactor's own timeline notes:
 *
 *   19:24:13  previous turn f0d77468 completes; thread goes idle
 *   19:33:00  five_hour REJECTED, resetsAt 19:50:00
 *   19:33:07  coil.auto-resume.scheduled — "Auto-resume scheduled in ~18 min"
 *   19:34:44  turn 64f7c4b7 requested AND completed, 508ms apart — a turn burned into
 *             the still-closed window, producing nothing
 *   19:51:34  coil.auto-resume.cancelled — "thread-advanced"       <-- the defect
 *   (never resumes; firedAtMs stays empty)
 *
 * The two sibling threads were mid-turn when the limit landed, so their baseline pinned a
 * turn that was still the latest at fire time. Nothing advanced, and both resumed at
 * 19:51:42 and 19:51:47. The only difference in the failing thread is the doomed turn.
 *
 * Why the guard misreads it: `cancelReason` treats "a different, non-null latest turn id"
 * as positive evidence the thread moved on (guards.ts:161-164). A turn that ran for half a
 * second against a closed limit and produced nothing is not the thread moving on — it is
 * the same blockage, observed again. This is the third instance of that class after #6 and
 * #39: a guard meant to detect a human taking the wheel, firing on ordinary machine
 * activity.
 *
 * NOTE FOR ANYONE FIXING THIS: do not edit this file or `reactorHarness.ts`. The fix
 * belongs in the feature (guards.ts / Reactor.ts / state.ts). This test encodes observed
 * production behaviour; changing it to match the code would erase the evidence.
 */

import type { ProviderRuntimeEvent } from "@t3tools/contracts";
import * as NodeServices from "@effect/platform-node/NodeServices";
import { describe, expect, it } from "@effect/vitest";
import * as Duration from "effect/Duration";
import * as Effect from "effect/Effect";
import * as Layer from "effect/Layer";
import * as Ref from "effect/Ref";
import * as TestClock from "effect/testing/TestClock";

import { AutoResumeReactorLive } from "../Reactor.ts";
import {
  appendedActivityKinds,
  appendedActivitySummaries,
  dispatchedTypes,
  makeReplayHarness,
  msToIso,
  readModel,
  REPLAY_THREAD_ID,
  settleQuiet,
  settleUntil,
  threadRow,
} from "./reactorHarness.ts";

/** The rejection shape the incident carried, verbatim from the provider log. */
const rejection = (resetsAtSeconds: number): ProviderRuntimeEvent =>
  ({
    type: "account.rate-limits.updated",
    eventId: "evt-five-hour-rejected",
    provider: "claudeAgent",
    threadId: REPLAY_THREAD_ID,
    createdAt: "2026-08-18T19:33:00.698Z",
    payload: {
      rateLimits: {
        type: "rate_limit_event",
        rate_limit_info: {
          status: "rejected",
          resetsAt: resetsAtSeconds,
          rateLimitType: "five_hour",
          overageStatus: "rejected",
          overageDisabledReason: "org_level_disabled",
          isUsingOverage: false,
        },
      },
    },
  }) as unknown as ProviderRuntimeEvent;

// Reset at 100s ⇒ resume due at 160s (60s safety margin). The incident's real interval was
// 17 minutes; only the ordering matters here.
const RESET_SECONDS = 100;

/**
 * The thread as it looked when the limit landed: idle, with the id of the turn that
 * finished nine minutes earlier still sitting in `latest_turn_id`.
 *
 * That the projection keeps a COMPLETED turn as `latest_turn_id` is itself observed from
 * the incident: turn 64f7c4b7 completed at 19:34:44 and is still the row's latest_turn_id.
 */
const idleAfterCompletedTurn = () =>
  threadRow({ sessionStatus: "ready", latestTurn: { turnId: "turn-old", state: "completed" } });

// Reset 100s ⇒ resume due at 160s. The incident's doomed turn completed 16 minutes BEFORE
// its arm was due (19:34:44 vs 19:51:00); scaled here to 104s, inside the shut window.
const DOOMED_COMPLETED_AT_MS = 104_000;
// A turn finished after the window reopened — a real human takeover, which must still cancel.
const TAKEOVER_COMPLETED_AT_MS = 200_000;

/**
 * The same thread after a turn burned into the closed window and died in half a second.
 *
 * `completedAt` is load-bearing: the guard compares it against the arm's `resumeAtMs`.
 * Omitting it would exercise only the no-evidence fallback and the scenario would pass no
 * matter which way the comparison ran — verified by mutation probe.
 */
const afterDoomedTurn = () =>
  threadRow({
    sessionStatus: "ready",
    latestTurn: {
      turnId: "turn-doomed",
      state: "completed",
      completedAt: msToIso(DOOMED_COMPLETED_AT_MS),
    },
  });

const advanceSteps = (steps: number) =>
  Effect.gen(function* () {
    for (let step = 0; step < steps; step++) {
      yield* TestClock.adjust(Duration.millis(30_000));
      yield* settleQuiet;
    }
  });

describe("incident 2026-08-18: doomed turn destroys the pending resume", () => {
  it.effect("resumes even though a doomed turn advanced the latest turn id", () =>
    Effect.gen(function* () {
      const harness = yield* makeReplayHarness({
        events: [rejection(RESET_SECONDS)],
        initialModel: readModel([idleAfterCompletedTurn()]),
      });

      yield* Effect.gen(function* () {
        yield* settleUntil(
          harness.store.listPending.pipe(Effect.map((pending) => pending.length === 1)),
          "the rejection to arm a resume",
        );

        // 19:34:44 — a turn is requested and completes 508ms later, against a window that
        // does not reopen for another 15 minutes. It produced nothing; all it did was
        // become the latest turn.
        yield* Ref.set(harness.modelRef, readModel([afterDoomedTurn()]));

        // 19:51:00 — the window has reopened and the resume is due.
        yield* advanceSteps(10);

        const commands = yield* Ref.get(harness.dispatched);

        // What production did: cancelled as "thread-advanced", pending cleared, no resume.
        expect(appendedActivitySummaries(commands)).not.toContain(
          "Auto-resume cancelled: thread-advanced.",
        );
        expect(appendedActivityKinds(commands)).not.toContain("coil.auto-resume.cancelled");

        // What it must do instead: fire. The thread is idle, the window is open, and
        // nothing about a 508ms failed turn says a human took over.
        expect(dispatchedTypes(commands)).toContain("thread.turn.start");
        expect(appendedActivityKinds(commands)).toContain("coil.auto-resume.resumed");
        expect(yield* harness.store.countFiredSince(REPLAY_THREAD_ID, 0)).toBe(1);
      }).pipe(Effect.provide(AutoResumeReactorLive.pipe(Layer.provideMerge(harness.deps))));
    }).pipe(Effect.scoped, Effect.provide(Layer.mergeAll(NodeServices.layer, TestClock.layer()))),
  );

  it.effect("CONTROL: a turn completed AFTER the window reopened still cancels as takeover", () =>
    Effect.gen(function* () {
      // The other side of the rule, and the reason it is a comparison rather than a blanket
      // exemption. If the arm fires here it would steamroll work a human really did after
      // the limit lifted. Without this case the corpus cannot tell a correct comparison
      // from an inverted one.
      const harness = yield* makeReplayHarness({
        events: [rejection(RESET_SECONDS)],
        initialModel: readModel([idleAfterCompletedTurn()]),
      });

      yield* Effect.gen(function* () {
        yield* settleUntil(
          harness.store.listPending.pipe(Effect.map((pending) => pending.length === 1)),
          "the rejection to arm a resume",
        );

        yield* Ref.set(
          harness.modelRef,
          readModel([
            threadRow({
              sessionStatus: "ready",
              latestTurn: {
                turnId: "turn-human",
                state: "completed",
                completedAt: msToIso(TAKEOVER_COMPLETED_AT_MS),
              },
            }),
          ]),
        );
        yield* advanceSteps(10);

        const commands = yield* Ref.get(harness.dispatched);
        expect(appendedActivitySummaries(commands)).toContain(
          "Auto-resume cancelled: thread-advanced.",
        );
        expect(dispatchedTypes(commands)).not.toContain("thread.turn.start");
        expect(yield* harness.store.countFiredSince(REPLAY_THREAD_ID, 0)).toBe(0);
      }).pipe(Effect.provide(AutoResumeReactorLive.pipe(Layer.provideMerge(harness.deps))));
    }).pipe(Effect.scoped, Effect.provide(Layer.mergeAll(NodeServices.layer, TestClock.layer()))),
  );

  it.effect("CONTROL: the sibling threads' shape still resumes (mid-turn when limited)", () =>
    Effect.gen(function* () {
      // 74b246f8 and 7245dfbe: rejected while a turn was running, that turn stayed latest,
      // both resumed. This must keep passing after any fix — it is the case that works.
      const harness = yield* makeReplayHarness({
        events: [rejection(RESET_SECONDS)],
        initialModel: readModel([
          threadRow({
            sessionStatus: "running",
            latestTurn: { turnId: "turn-live", state: "running" },
          }),
        ]),
      });

      yield* Effect.gen(function* () {
        yield* settleUntil(
          harness.store.listPending.pipe(Effect.map((pending) => pending.length === 1)),
          "the rejection to arm a resume",
        );

        // The limited turn settles; its id remains the latest.
        yield* Ref.set(
          harness.modelRef,
          readModel([
            threadRow({
              sessionStatus: "ready",
              latestTurn: { turnId: "turn-live", state: "completed" },
            }),
          ]),
        );
        yield* advanceSteps(10);

        expect(dispatchedTypes(yield* Ref.get(harness.dispatched))).toContain("thread.turn.start");
        expect(yield* harness.store.countFiredSince(REPLAY_THREAD_ID, 0)).toBe(1);
      }).pipe(Effect.provide(AutoResumeReactorLive.pipe(Layer.provideMerge(harness.deps))));
    }).pipe(Effect.scoped, Effect.provide(Layer.mergeAll(NodeServices.layer, TestClock.layer()))),
  );
});
